spring.application.name=api-gateway

spring.cloud.gateway.mvc.routes[0].id=product-service
spring.cloud.gateway.mvc.routes[0].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/product/**

spring.cloud.gateway.mvc.routes[1].id=order-service
spring.cloud.gateway.mvc.routes[1].uri=lb://ORDER-SERVICE
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/order/**

spring.cloud.gateway.mvc.routes[2].id=inventory-service
spring.cloud.gateway.mvc.routes[2].uri=lb://INVENTORY-SERVICE
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/inventory/**

spring.cloud.gateway.mvc.routes[3].id=notification-service
spring.cloud.gateway.mvc.routes[3].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/api/notification/**

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always

auth.service.validate-token-url=http://localhost:8081/api/v1/auth/validateToken
